### ISSUE TITLE
Loading assembly in Core.EngineFactory.InitializeEngines fails silently

### ISSUE THREAD

**Issue by manfredk** [mbarbac/Kerosene.ORM#1]
Within a web api controller I'm trying to get an IDataLink:

```
using Kerosene.ORM.Direct;
using Kerosene.Tools;
using Kerosene.ORM.SqlServer;
...
public MyEntity Get(int id) {
   IDataEngine kEngine = EngineFactory.Locate(name:"System.Data.SqlClient");
   var db = LinkFactory.Create(kEngine);
   ...
```

This is how I have initialized Kerosene in web.config:

```
    <configSections>
        <!--Entry to identify the handler for the Kerosene ORM configuration section.-->
        <section name="keroseneORM" type="Kerosene.ORM.Configuration.ORMConfiguration, Kerosene.ORM" />
    </configSections>
    <connectionStrings>
        <add name="DefaultConnection" connectionString="Data Source=[myServerName];Initial Catalog=[DBName];Integrated Security=True;MARS Connection=True" providerName="System.Data.SqlClient"/>
    </connectionStrings>
    <keroseneORM>
        <customEngines>
            <add id="SqlServer2012" type="Kerosene.ORM.SqlServer.v2012.Concrete.DataEngine" assembly="Kerosene.ORM.SqlServer.dll" />
        </customEngines>
        <connectionString name="DefaultConnection"/>
    </keroseneORM>
```

Kerosene fails silently on line 49 in Kerosene.ORM.Core.EngineFactory when loading assembly Kerosene.ORM.SqlServer:
`if ((asm = Assembly.LoadFrom(entry.AssemblyName)) == null)`
In this scenario I have included references to Kerosene libraries as project references (where the actual dlls are located in the respective git folders) and copyLocal is set to true - but the same behavior occurs when installing the references from nuget.

**Comment by mbarbac** [comment]
In your case I would rather have used:
     IDataEngine kEngine = EngineFactory.Locate("DefaultConnection");
Also, even if it is not mandatory, I would really like to encourage you to include in the connection string's contents a "MultipleActiveResultSets=true" section to support anything beyond basic maps.
Please try the above and let me know if it has solved your issue.

**Comment by manfredk** [comment]
Analyzing the code in ORM.Core.EngineFactory I boiled the issue down to the following:

ASP.NET projects use to shadow copy dlls to a temp directory. Shadow copying is for enabling Continue + Edit in Debug mode. Each dll is put in a different folder location under the temp directory (in my case this was "C:\Users\...\AppData\Local\Temp\Temporary ASP.NET Files\root\83edb32a\2056e6d2\assembly\dl3\d0608652\221fa726_a46bd001\Kerosene.ORM.SqlServer.dll" ). So the dll will not be found if it's just referenced by name. 

A workaround would be to load the original dll from the codebase folder. The following hack in Kerosene.ORM.Core.EngineFactory solved the issue for me:

```
public static void InitializeEngines()
{
    if (_Engines == null) _Engines = new List<IDataEngine>();
    _Engines.Clear();
        lock (_Engines)
    {
        var info = Configuration.ORMConfiguration.GetInfo();
        if (info != null && info.CustomEngines.Count != 0)
        {
            string currentDLL = Assembly.GetExecutingAssembly().GetName().Name + ".dll";
>> added    string codeBase = Path.GetDirectoryName(Assembly.GetExecutingAssembly().CodeBase);
>> added    if (codeBase.StartsWith("file:")) codeBase = new Uri(codeBase).LocalPath;       foreach (Configuration.CustomEngineElement entry in info.CustomEngines)
            {
                IDataEngine engine = null;
                Type type = null;
                Assembly asm = null;
>> added        string entryName = Path.Combine(codeBase, entry.AssemblyName);
...
```

I didn't check if this would break if the libraries are put into the GAC.

**Comment by mbarbac** [comment]
Aha! I was not aware of this "feature"... quick question: does it happen to you also in release mode?

**Comment by mbarbac** [comment]
Is already solved in the latest version. Thanks for having pointed it out.
